version: '3.8'

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: my-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Change this to your actual password
    ports:
      - "5432:5432"

  loomio:
    image: 4568910/loomio_image:v1
    container_name: loomio
    depends_on:
      - redis
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres # Ensure this matches the password set for Postgres
    network_mode: host

volumes:
  postgres-data:
