- new_discussion
- discussion_edited
- new_comment
- poll_created
- poll_edited
- poll_closing_soon
- poll_expired
- poll_closed_by_user
- poll_reopened
- outcome_created
- outcome_updated
- outcome_review_due
- stance_created
- stance_updated
